M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 25, Thursday 20:58:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-25T20:58:02-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.020
%
G90
G05
T1
X142.76Y-101.03
X142.76Y-117.97
X161.24Y-101.03
X161.24Y-117.97
T0
M30
